version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install --silent --no-progress -g serverless

  build:
    commands:
      - echo "Starting serverless deployment"
      - serverless deploy --stage $ENVIRONMENT --region $REGION --conceal --verbose
      - echo "Finished deployment"
